---
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  datacenter: kubernetes
  environment: production
info:
  component: WB3 K8s - Spring Cloud - NetFlix OSS Eureka Service Discovery
server:
  port: 8761
spring:
  application:
    name: wb3-k8s-msdiscovery
  profiles:
    active: default
