#This is the base configuration which all components for this project will inherit from
---
server:
  port: 80
spring:
  cloud:
    consul:
      config:
        enabled: false
        watch:
          enabled: false
      enabled: ${SERVICE_DISCOVERY_ENABLED}
      host: ${SERVICE_DISCOVERY_HOST}
      port: ${SERVICE_DISOVERY_PORT}
      token: ${SERVICE_DISCOVERY_TOKEN}
      discovery:
        healthCheckInterval: 15s
        instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
management:
  security:
    enabled: false
logging:
  level:
    ROOT: INFO
    org.springframework.web: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
