#This is the base configuration which all components for this project will inherit from
---
server:
  port: 80
management:
  security:
    enabled: false
# eureka:
#     instance:
#       instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
#     client:
#       serviceUrl:
#         defaultZone: https://wb3-k8s-msdiscovery.svc.cluster.local/eureka/
#       healthcheck:
#         enabled: true
#       registerWithEureka: true
#       fetchRegistry: true
#       registry-fetch-interval-seconds: 5
logging:
  level:
    ROOT: INFO
    org.springframework.web: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"