#This is the base configuration which all components for this project will inherit from
---
server:
  port: 80
management:
  security:
    enabled: false
eureka:
  datacenter: kubernetes
  environment: production
  client:
    fetch-registry: true
    serviceUrl:
      defaultZone: http://service-discovery.default.svc.cluster.local/eureka/
    healthcheck:
      enabled: true
  instance:
    instance-id: ${spring.application.name}:${random.int}
  registerWithEureka: true
  registry-fetch-interval-seconds: 15
logging:
  level:
    ROOT: INFO
    org.springframework.web: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
